sudo: true
language: node_js

git:
    submodules: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
      export CXX=g++-4.8;
    fi
  - git submodule update --init --recursive
  - gem install fpm --conservative || echo "FPM install failed"

compiler:
  - gcc
  - clang

node_js:
  - "10"

env:
  - DEFAULT_DELAY: 50

matrix:
  include:
    - node_js: "10"
      os: linux
    - node_js: "10"
      os: osx

script:
  - npm run lint;
  - npm run test:all:coverage;
  - bash scripts/package.sh true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - rpm

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
