sudo: true
language: node_js

git:
    submodules: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules;
      export CXX=g++-4.8;
    fi
  - git submodule update --init --recursive
  - gem install fpm --conservative || echo "FPM install failed"

compiler:
  - gcc
  - clang

node_js:
  - "10"

env:
  - DEFAULT_DELAY: 50

matrix:
  include:
    - node_js: "10"
      os: linux
    - node_js: "10"
      os: osx

script:
  - npm run lint;
  - npm run test:coverage;
  - sh scripts/run-e2e.sh;

before_deploy:
  - bash ./scripts/package.sh

deploy:
  - provider: s3
    access_key_id:
      secure: "C5eMLmRbwlQQtLIsEOhHr659JW87/N4PFBYsrAbDhr0T7CJrlQYkCgRvMMOgJFoq8QcDKVgPRTHKwtpgBwgjAcJIzOV57niI1DKHAdrgsQe+3dBe2bu77olV2JPhQWVwl2+5xS2oCbj/3bKJ2ykmA2I9GximVaV65MXnKbTdPTM="
    secret_access_key:
      secure: "eMyOkvuEveHR3e6VmQLvvWjklwLSeMw+bcPHxxjskeLfQc8bijmKM1ZFMWdmLUCaSjp5cse/XkSs5Sa+ObV2CUZatRz7XJxAMZjNnB3nApmR+vLRau2zQ8xxmHXbNeJMeMzhzpANB4vkXXEKJlbizjbFjL3nZ3duHlks2/lckVI="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
    on:
      branch: v4
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "UeDGbc9qehbKD63mNT4IebRpcPdctgqAlk7GNrz6/l6rPBsyLALd0o7mqHYcF0Dd2kMew1fDBiQEBUMTuFaggvGyKDmDkqGCdfo/6dGH07FzTpCwXisZ6u5eXo30deT5q94K1kaU17h8gmowBwmrU6iLXRrxCb6fkq58GX8P9tE="
    file_glob: true
    file:
      - "build/*.pkg"
      - "build/*.deb"
      - "build/*.rpm"
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

services:
  - redis-server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - rpm

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
