language: bash

services:
  - docker

script:
  - echo "No tests to run here"

jobs:
  include:
    - &create-packages
      stage: Create and upload linux packages
      install: curl -O https://raw.githubusercontent.com/deepstreamIO/deepstream.io/master/scripts/linux-package.sh
      script: bash linux-package.sh centos 7
    - <<: *create-packages
      script: bash linux-package.sh ubuntu xenial
    - <<: *create-packages
      script: bash linux-package.sh ubuntu bionic
    - <<: *create-packages
      script: bash linux-package.sh ubuntu cosmic
    - <<: *create-packages
      script: bash linux-package.sh debian jessie
    - <<: *create-packages
      script: bash linux-package.sh debian stretch

    - &test-packages
      stage: Download and test packages
      install: curl -O https://raw.githubusercontent.com/deepstreamIO/deepstream.io/master/scripts/linux-test.sh
      script: bash linux-test.sh centos 7
    - <<: *test-packages
      script: bash linux-test.sh ubuntu xenial
    - <<: *test-packages
      script: bash linux-test.sh ubuntu bionic
    - <<: *create-packages
      script: bash linux-test.sh ubuntu cosmic
    - <<: *test-packages
      script: bash linux-test.sh debian jessie
    - <<: *test-packages
      script: bash linux-test.sh debian stretch
