platform:
  - x64

os:
  - Visual Studio 2015

install:
  - ps: Install-Product node 10.15.1 x64
  - git submodule update --init --recursive
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  # Artifacts are packaged before before_deploy
  - bash scripts\package.sh
  - For /d %%d in ( build\** ) do MOVE %%d %cd%

artifacts:
  - path: 'build\*.zip'
    name: 'deepstream.io-release'

  - path: '**\*.zip'

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token: $GITHUB_TOKEN
    draft: true
    artifact: 'deepstream.io-release'
    on:
      appveyor_repo_tag: true

build: off
